# Generated by Django 3.0.7 on 2020-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemvalue', models.IntegerField()),
                ('itembool', models.BooleanField()),
                ('itememail', models.EmailField(max_length=30)),
            ],
        ),
    ]
