# Generated by Django 3.0.7 on 2020-08-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='itembool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='itemvalue',
            field=models.IntegerField(default=0),
        ),
    ]
